sudo: required
services:
  - docker

before_install:
  - docker build -t ridrupasinghe/sample-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ridrupasinghe/sample-docker-react npm run test