# language: node_js
# node_js:
#   - "14"

# branches:
#   only:
#     - master

sudo: required
services:
  - docker

# before_install:
#   - docker build -t ridrupasinghe/sample-docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true ridrupasinghe/sample-docker-react npm run test

# before_deploy:
#   - zip -r frontend.zip * .[^.]*
#   - echo "Deploying application..."

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  region: "eu-north-1"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-eu-north-1-992382845023"
  bucket_path: "frontend"
  # zip_file: "frontend.zip"
  on:
    branch: master
